- hosts: master
  tasks: 
  - name: install packages
    yum:
      name: 
        - httpd
        - wget
        - tree
        - vim
      state: latest

  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Stop httpd
    service:
      name: httpd
      state: stopped
      enabled: yes

  # - name: install wget
  #   yum:
  #     name: wget
  #     state: latest

  # - name: remove the Apache package
  #   yum:
  #     name: httpd
  #     state: absent

