- hosts: all
  tasks: 
  - name: install packages
    yum:
      name: httpd
      state: present
    notify: Install tree
  - name: install packages
    yum:
      name: vim
      state: present
    notify: Restart httpd
  
  handlers: 
  - name: Restart httpd
    service:
      name: httpd
      state: restarted
  - name: Install tree
    yum:
      name: tree
      state: present

      