# - hosts: vm1
#   tasks:
#   - hostname:
#       name: kaizen
# - hosts: vm1
#   tasks:
#   - hostname:
#       name: kaizen

# - hosts: vm2
#   tasks:
#   - hostname:
#       name: hello

# - hosts: aws1
#   become: true
#   tasks:
#   - hostname:
#       name: aws1

# - hosts: aws2
#   become: true
#   tasks:
#   - hostname:
#       name: aws2

- hosts: all
  become: true
  tasks:
  - hostname:
      name: "{{ inventory_hostname }}"
  
  - debug:
      msg: "{{ ansible_distribution }}"

  - name: Install Apache
    include_tasks: "{{ ansible_distribution }}.yml"
